### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by mjkabir40**
This PR is for profile management API with cosmos db.  
Please review. Any questions and suggestions are welcome.
Thanks

### CODE REVIEW

**Comment by s-laugh** [comment]
There are a lot of changes here and will take some time to review, has this work been reviewed prior to being merged to `develop`?

**Comment by mjkabir40** [comment]
> There are a lot of changes here and will take some time to review, has this work been reviewed prior to being merged to `develop`?
Thanks Shaun for taking the time to review. Sorry, I realize it is too much but no review done prior to this. Original Code was done with sql db and sequelize and now it is completed with cosmos db/Mongo and ready for review.  Develop is a working branch i created for this change. Thanks

**Comment by s-laugh** [comment]
Would it be possible to break this up into multiple PRs - I think it's simply too big to make an effective review.

> Original Code was done with sql db and sequelize

Also curious, no code was deleted, what happened to the original connections?

**Comment by mjkabir40** [comment]
okay, sure...Let me try to do multiple PR. 
If you look at commit from Jan 21, 2022, it should have deleted/added files. Thanks

**Comment by s-laugh** [comment]
> If you look at commit from Jan 21, 2022, it should have deleted/added files. Thanks

Looks like they may have gotten added back in, because this PR won't actually remove them.

**Pull request closed without merging**
